version: '3.8'

services:
  # Aplicação Next.js
  app:
    build: .
    container_name: mikrotik-manager-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://mikrotik:mikrotik123@postgres:5432/mikrotik_manager
      - JWT_SECRET=mikrotik-manager-super-secret-key-change-in-production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - mikrotik-network

  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: mikrotik-manager-db
    environment:
      POSTGRES_DB: mikrotik_manager
      POSTGRES_USER: mikrotik
      POSTGRES_PASSWORD: mikrotik123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - mikrotik-network

  # Redis para Cache e Sessões
  redis:
    image: redis:7-alpine
    container_name: mikrotik-manager-redis
    command: redis-server --requirepass redis123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - mikrotik-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: mikrotik-manager-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./logs:/var/log/nginx
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - mikrotik-network

  # Prometheus para Monitoramento
  prometheus:
    image: prom/prometheus:latest
    container_name: mikrotik-manager-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - mikrotik-network

  # Grafana para Dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: mikrotik-manager-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - mikrotik-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  mikrotik-network:
    driver: bridge
