version: '3.8'

services:
  app:
    build: .
    container_name: mikrotik-manager-app
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://mikrotik_user:mikrotik_pass@db:5432/mikrotik_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - mikrotik-network

  nginx:
    image: nginx:alpine
    container_name: mikrotik-manager-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - app
    networks:
      - mikrotik-network

  certbot:
    image: certbot/certbot
    container_name: mikrotik-manager-certbot
    restart: "no"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@flcomm.com.br --agree-tos --no-eff-email -d hotspot.flcomm.com.br

  db:
    image: postgres:15-alpine
    container_name: mikrotik-manager-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mikrotik_db
      POSTGRES_USER: mikrotik_user
      POSTGRES_PASSWORD: mikrotik_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-database.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - mikrotik-network

  redis:
    image: redis:7-alpine
    container_name: mikrotik-manager-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - mikrotik-network

  prometheus:
    image: prom/prometheus
    container_name: mikrotik-manager-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - mikrotik-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:

networks:
  mikrotik-network:
    driver: bridge
